#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
"$SCRIPT_DIR/../scripts/copy_files" "$SCRIPT_DIR/files"

podman build . -t vircadia-builder/ubuntu-21.04

